spring:
  application:
    name: quickcart-backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    hikari:
      maximum-pool-size: 5
      minimum-idle: 0
      connection-timeout: 10000
      idle-timeout: 300000
      max-lifetime: 900000

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas:
      - flyway
    default-schema: flyway
    create-schemas: true
    validate-on-migrate: true
    clean-disabled: true

server:
  address: 0.0.0.0
  port: ${PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: never

quickcart:
  auth:
    jwt:
      secret: ${JWT_SECRET}
      expiry: ${JWT_EXPIRY:12h}

  pagination:
    default-size: 20
    max-size: 100
